# Generated by Django 2.0.1 on 2018-01-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='departament',
            field=models.CharField(choices=[('AD', 'DT::ADMINISTRATION'), ('PR', 'DT::PROGRAMMING'), ('CO', 'DT::COMMERCE')], default='AD', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('BS', 'ET::BOSS'), ('TC', 'ET::TECNIC'), ('ST', 'ET::STUDENT')], default='TC', max_length=2),
        ),
    ]
