# Generated by Django 2.0.1 on 2018-01-04 19:50

from django.db import migrations, models
import employees.managers


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180104_2028'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', employees.managers.EmployeeManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('BS', 'ET::BOSS'), ('TC', 'ET::TECNIC'), ('ST', 'ET::STUDENT')], default='TC', max_length=2, verbose_name='FI::ROLE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.CharField(choices=[('AD', 'DT::ADMINISTRATION'), ('PR', 'DT::PROGRAMMING'), ('CO', 'DT::COMMERCE')], default='AD', max_length=2, verbose_name='FI::DEPARTAMENT'),
        ),
    ]
