# Generated by Django 2.0.1 on 2018-01-04 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180104_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
