# Generated by Django 2.0.1 on 2018-01-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_hired',
            field=models.BooleanField(default=True),
        ),
    ]
