# Generated by Django 2.0.1 on 2018-01-04 20:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_is_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='FI::HIRED_DATE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='FI::BOSS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_hired',
            field=models.BooleanField(default=True, verbose_name='FI::IS_HIRED'),
        ),
    ]
