# Generated by Django 2.0.1 on 2018-01-04 21:49

import django.contrib.auth.models
from django.db import migrations
import employees.managers


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180104_2111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('employees', employees.managers.EmployeeManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
