# Generated by Django 2.0.1 on 2018-01-04 22:25

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import employees.managers


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20180104_2249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('employees', employees.managers.EmployeeManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='is_traveling',
            field=models.BooleanField(default=False, verbose_name='FI::IS_TRAVELING'),
        ),
        migrations.AddField(
            model_name='employee',
            name='traveling_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='FI::TRAVELING_DATA'),
        ),
    ]
