# Generated by Django 2.0.1 on 2018-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20180104_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[(1, 'ET::BOSS'), (2, 'ET::TECNIC'), (3, 'ET::STUDENT')], default='TC', max_length=2, verbose_name='FI::ROLE'),
        ),
    ]
