# Generated by Django 2.0.1 on 2018-01-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20180107_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='FI:BIRTHDATE'),
        ),
    ]
